In [ ]:
#Work with pandas
import pandas as pd

In [ ]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
a = pd.Series([44,1,2,3,4,6])
print(type(a))

<class 'pandas.core.series.Series'>


In [ ]:
a.axes

[RangeIndex(start=0, stop=6, step=1)]

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.size

6

In [ ]:
a.ndim

1

In [ ]:
a.values

array([44,  1,  2,  3,  4,  6])

In [ ]:
#Head function for first n element
a.head()

0    44
1     1
2     2
3     3
4     4
dtype: int64

In [ ]:
#Tail function for last n element
a.tail()

1    1
2    2
3    3
4    4
5    6
dtype: int64

In [ ]:
#Index function for change index number in pandas array
pd.Series([99,122,34,55,66,34], index = [1, 3, 5, 7, 8, 9])

1     99
3    122
5     34
7     55
8     66
9     34
dtype: int64

In [ ]:
#Index process with string
pd.Series([99, 22, 332, 94, 5], index = ['a', 'b', 'c', 'd', 'e'])

a     99
b     22
c    332
d     94
e      5
dtype: int64

In [ ]:
b = pd.Series([99, 22, 332, 94, 5], index = ['a', 'b', 'c', 'd', 'e'])
print(b['a'])
print(b['b'])


99
22
a     99
b     22
c    332
dtype: int64


In [ ]:
#Slicing process
print(b['a' : 'c'])

In [ ]:
#Dictinoary in pandas series

d = pd.Series({
    'reg' : 10,
    'log' : 11,
    'cart' : 120
})
print(d)
print(type(d))

reg      10
log      11
cart    120
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
#Connect two series
pd.concat([a, d])

0        44
1         1
2         2
3         3
4         4
5         6
reg      10
log      11
cart    120
dtype: int64

In [ ]:
#Access index
a.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
#Acess keys
a.keys

<bound method Series.keys of 0    44
1     1
2     2
3     3
4     4
5     6
dtype: int64>

In [ ]:
s = pd.Series([121, 200, 150, 99],
              index = ['reg', 'log', 'cart', 'rf'])

In [ ]:
s.index

Index(['reg', 'log', 'cart', 'rf'], dtype='object')

In [ ]:
#Access keys
s.keys

<bound method Series.keys of reg     121
log     200
cart    150
rf       99
dtype: int64>

In [ ]:
#Access items
list(s.items())

[('reg', 121), ('log', 200), ('cart', 150), ('rf', 99)]

In [ ]:
#Check element
'reg' in s

True

In [ ]:
#Create DataFrame in pandas
l = [1, 2, 39, 67, 90]

pd.DataFrame(l, columns = ['Variable_name'])



Variable_name
0              1
1              2
2             39
3             67
4             90

In [ ]:
import numpy as np
m = np.arange(1, 10).reshape((3, 3))
print(m)

print('\n')
df = pd.DataFrame(m, columns = ['var1', 'var2', 'var3'])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


   var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9


In [ ]:
#First n element in Dataframe
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['var1', 'var2', 'var3'], dtype='object')]

In [ ]:
df.ndim

2

In [ ]:
df.size

9

In [ ]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
import numpy as np

s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)


In [ ]:
#Connection of numpy array and dictinoaries

d = {
    'var1' : s1,
    'var2' : s2,
    'var3' : s3
}
print(d)
print(type(d))

{'var1': array([1, 6, 0, 9, 3]), 'var2': array([9, 2, 1, 7, 5]), 'var3': array([0, 1, 8, 3, 0])}
<class 'dict'>


In [ ]:
df = pd.DataFrame(d)
print(df)

   var1  var2  var3
0     1     9     0
1     6     2     1
2     0     1     8
3     9     7     3
4     3     5     0


In [ ]:
#Delete function in Pandas
df.drop(1, axis = 0)
df.drop(2, axis = 0)


var1  var2  var3
0     1     9     0
1     6     2     1
3     9     7     3
4     3     5     0

In [ ]:
import numpy as np
import pandas as pd

m = np.random.randint(1, 30, size = (10, 3))
df = pd.DataFrame(m, columns = ['var1', 'var2', 'var3'])

print(m, '\n')
print(df)

[[13  4  6]
 [19  2 20]
 [26 17 11]
 [22 24 26]
 [13 16 27]
 [20  2  2]
 [27 23 26]
 [29 10  2]
 [16 25  7]
 [26 17  8]] 

   var1  var2  var3
0    13     4     6
1    19     2    20
2    26    17    11
3    22    24    26
4    13    16    27
5    20     2     2
6    27    23    26
7    29    10     2
8    16    25     7
9    26    17     8


In [ ]:
#Loc & iloc
#1.loc
df.loc[0:3]

var1  var2  var3
0    13     4     6
1    19     2    20
2    26    17    11
3    22    24    26

In [ ]:
#2.iloc
df.iloc[0:3]

var1  var2  var3
0    13     4     6
1    19     2    20
2    26    17    11

In [ ]:
df.iloc[:3, :2]

var1  var2
0    13     4
1    19     2
2    26    17